name = "therapy-finder"
compatibility_date = "2023-01-01"

[[d1_databases]]
binding = "DB"                # Environment variable name
database_name = "local-db"    # Database name
database_id = "local"         # ID for local development
